language: php
php:
- 7.1
- 7.2
- 7.3
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - dev
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
- WP_VERSION=latest
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- sudo apt-get -qq update
install:
- composer install
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv
  config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh pce_test root '' localhost $WP_VERSION
script:
- vendor/bin/phpunit --configuration=phpunit.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml .
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: DrG6DTj/7xGBszmuqSVG6zUawAO+P1T1QeaZh3/Lhzd3evCNd+K+JorL75H0d8THXzwhyywXMgnCXhdmALqCJ9EfidTlvstR3J3GeTgDCLRsSpvzNE/zS/fUcKZjGGJ+eKawnNv37yYpIBRKc+FiQvyrl4pNwIKg94YmLWt5AwuTqP0H9C5KdGcYNF/N1y3rIH7VAdU4CVO3BZ74Bt7ZRO3RSf0odGA3Gh3TkPy4jv+oqxRESDM0ORKdYVOM3q557LAEoh4zbZePm+KBIUR9UKe5MOjDJxpH+hMZ8c715Gt1bV6FMIUMmtDHNZ3017aUoRiIgY8Mp5PVcIhWLtXyZbjejwn4LlzBlHrnqNnlqw8ks5m6QnLPyj5wi+k3DqH/mMFd+MuApZBfgSIUPU/bJiErPXD4PbEBZurh2Xgmtf7HxXUbeaA6OLlglMU2lHPzS8cpr8uxWdgPfik06uVrTMAl7v2VUZqBzKRKLiPl9RLT5q30U+BdvtQnvQA5qQq9wfsoZWmG/SKeI20WeaW64EdaE4eBm/A9AH92XYcP1MMdizQOP00pi00kk9PoXAcqKq7HuY2ZfAIr1eTCDg8Y5HmaqB9hPhNk7PmK4l/bWMlTsL6zAV94BXR5S2xWuB4D3mPTLd7yPMP8friVC0tj+D7NzIbaptHqRaxYCT3/lQQ=
  file: pressbooks-cc-export-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: BCcampus/pressbooks-cc-export
    branch: dev
